import type { AffirmationTone } from "./types";

const GENTLE: string[] = [
  `Small steps, steady rhythm. You're building something that lasts.`,
  `Showing up softly still counts as showing up.`,
  `Small repetitions, kept honestly, become the person you're trying to be.`,
  `You don't have to be perfect today. You just have to be here.`,
  `Consistency is kinder than intensity. Be kind to yourself today.`,
  `A quiet effort is still an effort. Let today be quiet if it needs to be.`,
  `Progress rarely feels like progress. Trust the rhythm anyway.`,
  `You are allowed to begin again, as many times as it takes.`,
  `The days you almost skipped are the ones that matter most.`,
  `Gently does it. The habit is the practice, not the streak.`,
  `What you tend to, grows. Tend gently today.`,
  `Rest is part of the rhythm too. Honour what today asks of you.`,
  `You're not behind. You're exactly where the practice meets you.`,
  `One small kindness to your future self is enough for today.`,
  `The smallest version of the habit still counts. Do that one.`,
  `Soft and steady outlasts hard and brief.`,
  `Today doesn't need to be remarkable. It just needs to happen.`,
  `You can keep a promise to yourself quietly. No one else needs to see.`,
  `Let the bar be low enough to step over. Then step over it.`,
  `Returning is its own kind of strength. Welcome back.`,
  `A gentle rhythm is still a rhythm. Keep it loosely.`,
  `You've done hard things before. This one is smaller than it looks.`,
  `Be patient with the slow days. They're doing more than they seem.`,
  `The point isn't to never miss. It's to never quit.`,
  `Today's effort doesn't have to be yesterday's. Meet yourself here.`,
  `You are building a life one ordinary morning at a time.`,
  `Tiny and consistent beats grand and abandoned.`,
  `Let yourself off the hook, then quietly do the thing anyway.`,
  `Your worth isn't measured in checkmarks. Do it because it's kind to you.`,
  `The habit will still be here tomorrow. So will you.`,
  `Small is sustainable. Sustainable is what changes you.`,
  `Give today what you have, not what you wish you had.`,
  `There's no streak to protect, only a self to care for.`,
  `Easy days keep you in the game. Take the easy version today.`,
  `You can do this gently. You can do this imperfectly. Just do this.`,
  `A single page, a single breath, a single step. That's plenty.`,
  `Be the friend to yourself you'd be to someone you love.`,
  `Momentum is built quietly, in moments no one applauds.`,
  `You don't have to feel ready. You only have to feel willing.`,
  `Slow progress is still progress moving in your direction.`,
  `Forgive the gap, then close it softly. No drama needed.`,
  `The habit is a relationship, not a test. Keep showing up.`,
  `Today you get to choose ease and still move forward.`,
  `You're allowed to make this smaller until it's doable.`,
  `Steadiness is a quiet superpower. You have more than you think.`,
  `Let it be enough to simply not stop.`,
  `Your effort today plants something you'll harvest without noticing.`,
  `Be gentle with the beginning. Beginnings are tender.`,
  `The rhythm forgives a missed beat. Just find the next one.`,
  `You are not your worst day. You're the sum of your returns.`,
  `Do the kind thing for tomorrow-you, in whatever size fits today.`,
  `Soft consistency reshapes a life more than fierce bursts.`,
  `You can rest without quitting. They are not the same thing.`,
  `Let today be a low, honest note. The song still counts.`,
  `What feels like nothing today compounds into everything later.`,
  `Keep the promise small enough that you can always keep it.`,
  `There is grace in the ordinary repetition. Take it.`,
  `You showed up. That alone is worth something today.`,
  `The gentlest path forward is still forward.`,
  `Trust that small care, repeated, becomes real change.`,
  `You don't owe anyone intensity. You only owe yourself presence.`,
  `Begin where you are, with what today actually allows.`,
  `A habit kept loosely for years beats one gripped for a week.`,
  `Let the practice be a soft place to land, not a wall to climb.`,
  `Your steadiness doesn't need witnesses to be true.`,
  `Today's small yes is a gift to every tomorrow.`,
  `Be unhurried. The good things take the time they take.`,
  `You can always do less, and still not do nothing.`,
  `The kind choice and the consistent choice are often the same one.`,
  `Quiet effort, repeated with care, is how people actually change.`,
  `Meet the day at its own pace, then take one step.`,
  `You are allowed to find this easy today.`,
  `Gentleness is not the opposite of discipline. It's the sustainable kind.`,
  `Let the habit hold you lightly. Light holds last longest.`,
  `The smallest honest effort keeps the thread unbroken.`,
  `You're doing better than the harsh voice says you are.`,
  `One soft repetition today. That's the whole assignment.`,
  `Lower the stakes until showing up feels possible. Then show up.`,
  `Your future self is built from quiet mornings like this one.`,
  `It counts even when it's small. Especially when it's small.`,
  `Be tender with the process and the process will be good to you.`,
  `You can keep going without going hard.`,
  `The river shapes the stone slowly. So does your steadiness.`,
  `Today, choose the version of the habit you can actually finish.`,
  `Returning gently is more powerful than never having left.`,
  `There's no rush. There's only the next small, caring choice.`,
  `You're allowed to do this badly and still call it done.`,
  `Soft starts still start. Begin softly.`,
  `The practice loves you back when you keep it kindly.`,
  `Let enough be enough today, and let that be progress.`,
  `A calm, repeated effort is quietly rebuilding you.`,
  `You can be both gentle with yourself and faithful to the habit.`,
  `Small today. Small tomorrow. Remarkable in a year.`,
  `The point of the rhythm is to carry you, not to grade you.`,
  `Honour the day you're actually in, and do one small thing.`,
  `You kept showing up. That's the whole secret, gently held.`,
  `Be kind, begin small, and let consistency do the rest.`,
  `Today is enough. You are enough. One small step is enough.`,
  `Let today be small and honest. That's a full success.`,
  `Keep the thread unbroken with one gentle stitch today.`,
];

const DIRECT: string[] = [
  `Do the small thing now. The momentum follows the action.`,
  `You know what today needs. Go do it.`,
  `Don't negotiate with the plan. Just start.`,
  `One rep. One page. One step. Begin.`,
  `Future you is built by what you do in the next hour.`,
  `Show up. That's the whole job today.`,
  `Discipline is just remembering what you want. Remember.`,
  `Stop waiting to feel ready. Start, and ready will catch up.`,
  `The habit doesn't care about your mood. Do it anyway.`,
  `Action first. Motivation is a byproduct, not a prerequisite.`,
  `Close the gap between knowing and doing. Today.`,
  `Make the choice your future self would thank you for.`,
  `Quit overthinking it. The work is simpler than the worry.`,
  `You don't need permission. You need to begin.`,
  `Do it while it's inconvenient. That's when it counts.`,
  `The plan only works if you do. So do.`,
  `Five minutes now beats a perfect hour that never comes.`,
  `Stop measuring how you feel. Start measuring what you did.`,
  `The excuse is convincing. Do it anyway.`,
  `Win the morning by doing the thing before you can argue.`,
  `You already know the move. Make it.`,
  `Don't break the chain today. Add one more link.`,
  `Effort now. Comfort never built anything worth having.`,
  `Decide once, then stop deciding. Just execute.`,
  `The hard part is starting. Make starting non-negotiable.`,
  `Be the person who does it, not the one who means to.`,
  `Less planning, more doing. Move.`,
  `Your goals don't care about your excuses. Act.`,
  `Do the boring rep. The boring reps are the whole game.`,
  `Stop scrolling past your own intentions. Begin.`,
  `Momentum is a decision. Decide now.`,
  `You have time for this. You're choosing not to. Choose better.`,
  `The version of you that you want is on the other side of this rep.`,
  `No motivation? Good. Do it without it.`,
  `Cut the warm-up. Start cold and start now.`,
  `Discipline today buys freedom tomorrow. Pay it.`,
  `You're one action away from feeling proud. Take it.`,
  `Don't wait for Monday. Monday is a story. Today is real.`,
  `Make it happen before you talk yourself out of it.`,
  `The work doesn't get easier. You get better. Start.`,
  `Earn tonight's rest by doing the thing now.`,
  `Show up especially when you don't want to. That's the point.`,
  `Stop bargaining. The deal is simple: do it.`,
  `You wrote the goal. Now honour it with action.`,
  `Half-effort still beats no effort. Give what you've got, now.`,
  `The clock's running. Spend the next minutes on what matters.`,
  `Be relentless about the small stuff. The small stuff is everything.`,
  `Done is the standard today. Not perfect. Done.`,
  `Your future is being decided right now. Decide well.`,
  `Skip the story about how hard it is. Just do the next rep.`,
  `Action cures the doubt. Move and the doubt quiets.`,
  `You don't rise to your goals. You fall to your habits. Build this one.`,
  `Make the choice now while it's still yours to make.`,
  `The work is waiting. Stop making it wait.`,
  `Be louder in action than in intention.`,
  `Get it done early so it can't get away from you.`,
  `You've negotiated long enough. Execute.`,
  `Prove it to yourself today. Reps over rhetoric.`,
  `The thing you're avoiding is the thing to do first.`,
  `Treat the small commitment like it's non-negotiable. Because it is.`,
  `Start ugly. Start late. Just start.`,
  `Don't let comfort make today's decision for you.`,
  `You said you would. So do.`,
  `Beat resistance by moving before it sets up.`,
  `One honest rep is worth a thousand good intentions.`,
  `Stop waiting for the mood. Manufacture it through motion.`,
  `Today is a rep in becoming who you said you'd be. Take it.`,
  `Resistance is loudest right before you start. Start.`,
  `You don't need a better day. You need to begin this one.`,
  `Make the next right move. Then the next. That's it.`,
  `The goal is downstream of today's action. Act.`,
  `Hold the line on the small daily thing. No exceptions today.`,
  `Quit waiting to be inspired. Be consistent instead.`,
  `Put the rep on the board before you do anything else.`,
  `You're capable right now, not someday. Use it.`,
  `The shortcut is that there's no shortcut. Do the work.`,
  `Make it automatic by doing it again today. No debate.`,
  `Future-you is watching this moment. Give them something.`,
  `Stop protecting your comfort. Start protecting your progress.`,
  `Be the kind of person who just handles it. Handle it.`,
  `You can rest after. Right now, move.`,
  `The habit is a vote for who you're becoming. Cast it.`,
  `Don't outsource today to tomorrow. Tomorrow's busy too.`,
  `Do it badly if you must, but do it.`,
  `Cut the deliberation. The answer is yes, now go.`,
  `Today's discipline is tomorrow's momentum. Bank it.`,
  `You're not tired, you're untested. Begin and find out.`,
  `Make showing up boring and automatic. Show up.`,
  `Less talking about it. More being about it.`,
  `The reps you skip are the ones that haunt you. Don't skip.`,
  `Win the rep in front of you. Ignore the rest.`,
  `You have everything you need to start. So start.`,
  `Stop renegotiating the commitment. Just meet it.`,
  `Action is the only thing that moves the needle. Move it.`,
  `Be impatient with excuses and patient with results. Begin.`,
  `Do it now so future-you isn't cleaning up the gap.`,
  `The standard is simple: did you do it? Make the answer yes.`,
  `Turn the intention into a rep before the day eats it.`,
  `Show your goals you're serious. Today. With action.`,
  `You already decided. Now go be someone who follows through.`,
];

function pickFor(day: string, tone: AffirmationTone): string {
  const list = tone === "direct" ? DIRECT : GENTLE;
  let h = 0;
  for (let i = 0; i < day.length; i++) h = (h * 31 + day.charCodeAt(i)) | 0;
  const idx = Math.abs(h) % list.length;
  return list[idx];
}

export async function getAffirmation(
  day: string,
  tone: AffirmationTone,
): Promise<string> {
  return pickFor(day, tone);
}

export const _counts = { gentle: GENTLE.length, direct: DIRECT.length };
